export const NAICS = {
  2022: [
    { id: "11", define: "Agriculture, Forestry, Fishing and Hunting" },
    { id: "21", define: "Mining, Quarrying, and Oil and Gas Extraction" },
    { id: "22", define: "Utilities" },
    { id: "23", define: "Construction" },
    { id: "31-33", define: "Manufacturing" },
    { id: "42", define: "Wholesale Trade" },
    { id: "44-45", define: "Retail Trade" },
    { id: "48-49", define: "Transportation and Warehousing" },
    { id: "51", define: "Information" },
    { id: "52", define: "Finance and Insurance" },
    { id: "53", define: "Real Estate and Rental and Leasing" },
    { id: "54", define: "Professional, Scientific, and Technical Services" },
    { id: "55", define: "Management of Companies and Enterprises" },
    {
      id: "56",
      define:
        "Administrative and Support and Waste Management and Remediation Services",
    },
    { id: "61", define: "Educational Services" },
    { id: "62", define: "Health Care and Social Assistance" },
    { id: "71", define: "Arts, Entertainment, and Recreation" },
    { id: "72", define: "Accommodation and Food Services" },
    { id: "81", define: "Other Services (except Public Administration)" },
    { id: "92", define: "Public Administration" },
  ],
  2017: [
    { id: "11", define: "Agriculture, Forestry, Fishing and Hunting" },
    { id: "21", define: "Mining, Quarrying, and Oil and Gas Extraction" },
    { id: "22", define: "Utilities" },
    { id: "23", define: "Construction" },
    { id: "31-33", define: "Manufacturing" },
    { id: "42", define: "Wholesale Trade" },
    { id: "44-45", define: "Retail Trade" },
    { id: "48-49", define: "Transportation and Warehousing" },
    { id: "51", define: "Information" },
    { id: "52", define: "Finance and Insurance" },
    { id: "53", define: "Real Estate and Rental and Leasing" },
    {
      id: "54",
      define: "Professional, Scientific, and Technical Services",
    },
    { id: "55", define: "Management of Companies and Enterprises" },
    {
      id: "56",
      define:
        "Administrative and Support and Waste Management and Remediation Services",
    },
    { id: "61", define: "Educational Services" },
    { id: "62", define: "Health Care and Social Assistance" },
    { id: "71", define: "Arts, Entertainment, and Recreation" },
    { id: "72", define: "Accommodation and Food Services" },
    { id: "81", define: "Other Services (except Public Administration)" },
    { id: "92", define: "Public Administration" },
  ],
};
